version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      bash -c "chmod +x /app/executables/Rhubarb-Lip-Sync-1.13.0-Linux/rhubarb &&
               python -u app.py"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 